---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: helm
  namespace: kube-system
rules:
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - get
  resourceNames:
  - tiller-deploy
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm_default
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: helm
subjects:
- kind: ServiceAccount
  name: helm
  namespace: default
