# Provision steps:
#
# helm repo add jetstack https://charts.jetstack.io
# helm install cert-manager jetstack/cert-manager --version 1.4.0 --namespace kube-system --values ./cert-manager.yaml
# $ kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.4.0/cert-manager.crds.yaml

global:
  rbac:
    create: true

replicaCount: 1
resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

webhook:
  enabled: true
  replicaCount: 1

  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi

cainjector:
  enabled: true
  replicaCount: 1

  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 20m
      memory: 128Mi