# Provision steps:
#
# helm repo add grafana https://grafana.github.io/helm-charts
# helm install loki grafana/loki-stack --version 2.4.1 --namespace monitoring --values ./loki-stack.yaml

loki:
  enabled: true
  replicas: 1

  persistence:
    enabled: true
    storageClassName: azure-file-standard-lrs-delete

  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

promtail:
  enabled: true

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi
