# Provision steps:
#
# helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
# helm repo add kube-state-metrics https://kubernetes.github.io/kube-state-metrics
# helm install prometheus prometheus-community/prometheus --version 14.2.0 --namespace monitoring --values ./prometheus.yaml
rbac:
  create: true

podSecurityPolicy:
  enabled: true

server:
  replicaCount: 1
  statefulSet:
    enabled: true

  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 250m
      memory: 2Gi

  persistentVolume:
    enabled: true
    storageClass: azure-file-standard-lrs-retain

  retention: "7d"

nodeExporter:
  resources:
    requests: 
      cpu: 10m
      memory: 50Mi
    limits:
      cpu: 200m
      memory: 100Mi

kubeStateMetrics:
  enabled: true

alertmanager:
  enabled: false

pushgateway:
  enabled: false