apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-devops
  namespace: kcidemo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-devops
  namespace: kcidemo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: azure-devops
  namespace: kcidemo