#############################################################
# Terraform Apply/Destroy
# 
# This pipeline will allow a Terraform template to be
# applied and destroyed.
#############################################################
name: 'Terraform CI'

trigger: 'none'
# trigger:
#   batch: true
#   branches:
#     include:
#     - master
#   paths:
#     include:
#     - 'infrastructure/terraform/kcidemo'

variables:
- group: 'shared-terraform'
## Contains:
## * terraformStateSubscriptionName
## * terraformStateStorageAccountName
## * terraformAzureSubscription
## * terraformWorkingDirectoryBase
## Set these variables on pipeline creation or uncomment and update in here if it will be static
- name: 'templateName'
  value: 'kcidemo'
# - name: 'terraformAdditionalArgs'
#   value: 'REPLACE_ME'
# - name: 'terraformApply'
#   value: 'false'
# - name: 'terraformDestroy'
#   value: 'false'

pool:
  vmImage: 'ubuntu-latest'

stages:
# Template stage used to do a Terraform run.
# This cannot be reused due to jobs requiring unique names.
- template: '/.devops/pipelines/templates/terraformRun.tpl.stage.yml'
  parameters:
    terraformWorkingDirectory: '$(terraformWorkingDirectoryBase)/$(templateName)'
    terraformStateAzureSubscriptionName: '$(terraformStateAzureSubscriptionName)'
    terraformStateStorageAccountName: '$(terraformStateStorageAccountName)'
    azureSubscription: '$(terraformAzureSubscription)'
    terraformAdditionalArgs: '-var-file tfvars/default.tfvars'
    terraformApply: '$(terraformApply)'
    terraformInputVariables:
      resource_prefix: '$(resourcePrefix)'

# This creates resources in the kcidemo namespace for us
- stage: 'kubernetesConfigure'
  displayName: 'Configure Kubernetes'
  condition: succeeded()

  jobs:
  - job: 'createKCIResources'
    displayName: 'Create KCI Resources'
    steps:
    - template: '/.devops/pipelines/templates/terraformInitAzure.tpl.steps.yml'
      parameters:
        terraformWorkingDirectory: '$(terraformWorkingDirectoryBase)/$(templateName)'
        terraformStateAzureSubscriptionName: '$(terraformStateAzureSubscriptionName)'
        terraformStateStorageAccountName: '$(terraformStateStorageAccountName)'
        azureSubscription: '$(terraformAzureSubscription)'
        # Ensure terraformWorkspace is set here if set in the Apply section

    - task: KubectlInstaller@0
      name: 'installKubectl'
      displayName: 'Install Kubectl'

    - task: Bash@3
      name: 'createKcidemoResources'
      displayName: 'Create kcidemo resources'
      inputs:
        targetType: 'inline'
        script: |
          terraform output aks_config > config
          kubectl apply -f ../../kubernetes/kcidemo
          rm -f config
        workingDirectory: '$(terraformWorkingDirectoryBase)/$(templateName)'
      env:
        KUBECONFIG: './config'

# Steps below will perform a DESTROY operation on existing infrastructure.
- stage: 'destroy'
  displayName: 'Terraform Destroy'
  condition: and(always(), eq(variables['terraformDestroy'], 'true'))
  variables:
    TF_IN_AUTOMATION: true

  jobs:
  - job: 'destroy'
    displayName: 'Terraform Destroy'
    steps:
    - template: '/.devops/pipelines/templates/terraformInitAzure.tpl.steps.yml'
      parameters:
        terraformWorkingDirectory: '$(terraformWorkingDirectoryBase)/$(templateName)'
        terraformStateAzureSubscriptionName: '$(terraformStateAzureSubscriptionName)'
        terraformStateStorageAccountName: '$(terraformStateStorageAccountName)'
        azureSubscription: '$(terraformAzureSubscription)'

    - task: Bash@3
      name: 'destroy'
      displayName: 'Terraform Destroy'
      inputs:
        targetType: 'inline'
        script: 'terraform destroy -input=false -auto-approve'
        workingDirectory: '$(terraformWorkingDirectoryBase)/$(templateName)'
      env:
        ARM_TENANT_ID: '$(ARM_TENANT_ID)'
        ARM_SUBSCRIPTION_ID: '$(ARM_SUBSCRIPTION_ID)'
        ARM_CLIENT_ID: '$(ARM_CLIENT_ID)'
        ARM_CLIENT_SECRET: '$(ARM_CLIENT_SECRET)'
        TF_VAR_resource_prefix: '$(resourcePrefix)'
