---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk-standard-retain
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
parameters:
  kind: Managed
  storageaccounttype: Standard_LRS
  cachingmode: None
allowVolumeExpansion: true
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk-standard-delete
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
parameters:
  kind: Managed
  storageaccounttype: Standard_LRS
  cachingmode: None
allowVolumeExpansion: true
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk-premium-retain
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
parameters:
  kind: Managed
  storageaccounttype: Premium_LRS
  cachingmode: None
allowVolumeExpansion: true
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk-premium-delete
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
parameters:
  kind: Managed
  storageaccounttype: Premium_LRS
  cachingmode: None
allowVolumeExpansion: true
volumeBindingMode: Immediate
