#############################################################
# Packer Build
# 
# This pipeline will build a Packer image in Azure.
#############################################################
name: 'Packer CI'

trigger: 'none'
# trigger:
#   batch: true
#   branches:
#     include:
#     - master
#   paths:
#     include:
#     - 'path/to/packer/root'

variables:
- group: 'shared-packer'
## Contains:
## * agentPool
## * packerAzureSubscription
## * packerWorkingDirectoryBase
## Set these variables on pipeline creation or uncomment and update in here if it will be static
# - name: 'templateName'
#   value: 'REPLACE_ME'
# - name: 'packerAzureLocation'
#   value: 'REPLACE_ME'
# - name: 'packerAzureResourceGroup'
#   value: 'REPLACE_ME'

pool:
  name: '$(agentPool)'

stages:
- template: '/.devops/pipelines/templates/packerBuild.tpl.stage.yml'
  parameters:
    packerWorkingDirectory: '$(packerWorkingDirectoryBase)/$(templateName)'
    azureSubscription: '$(packerAzureSubscription)'
    packerAzureLocation: '$(packerAzureLocation)'
    packerAzureResourceGroup: '$(packerAzureResourceGroup)'
    packerTemplateFile: 'REPLACE_ME'
