---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # Set email to a valid email address
    email: ''
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    # Configure solver as required - see https://cert-manager.io/docs/configuration/acme/
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Set email to a valid email address
    email: ''
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    # Configure solver as required - see https://cert-manager.io/docs/configuration/acme/
    - http01:
        ingress:
          class: nginx